-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 17:26:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `dataCadastro` DATE NOT NULL DEFAULT now(),
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_modelo_recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_modelo_recurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_modelo_recurso` (
  `idModelo` INT NOT NULL AUTO_INCREMENT,
  `modelosRecursos` TEXT(1000) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `tb_usuario_idUsuario` INT NOT NULL COMMENT 'id do usuario que criou o recurso',
  PRIMARY KEY (`idModelo`),
  INDEX `fk_tb_modelo_recurso_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC),
  CONSTRAINT `fk_tb_modelo_recurso_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_informacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_informacoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_informacoes` (
  `idInformacoes` INT NOT NULL AUTO_INCREMENT,
  `orgaoAutuador` VARCHAR(45) NOT NULL,
  `ufOrgao` VARCHAR(2) NOT NULL,
  `numeroInfracao` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `ufPlaca` VARCHAR(2) NOT NULL,
  `marcaVeiculo` VARCHAR(45) NOT NULL,
  `modeloVeiculo` VARCHAR(45) NOT NULL,
  `renavam` VARCHAR(11) NOT NULL,
  `dataInfracao` DATE NOT NULL,
  `horarioInfracao` TIME(5) NOT NULL,
  `localidadeIngracao` VARCHAR(45) NOT NULL,
  `ufInfracao` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idInformacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_multas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_multas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_multas` (
  `idMultas` INT NOT NULL AUTO_INCREMENT,
  `tb_informacoes_idInformacoes` INT NOT NULL,
  `tb_modelo_recurso_idModelo` INT NOT NULL,
  PRIMARY KEY (`idMultas`),
  INDEX `fk_tb_multas_tb_informacoes1_idx` (`tb_informacoes_idInformacoes` ASC),
  INDEX `fk_tb_multas_tb_modelo_recurso1_idx` (`tb_modelo_recurso_idModelo` ASC),
  CONSTRAINT `fk_tb_multas_tb_informacoes1`
    FOREIGN KEY (`tb_informacoes_idInformacoes`)
    REFERENCES `mydb`.`tb_informacoes` (`idInformacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_multas_tb_modelo_recurso1`
    FOREIGN KEY (`tb_modelo_recurso_idModelo`)
    REFERENCES `mydb`.`tb_modelo_recurso` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `tb_modelo_recurso_idModelo` INT NOT NULL,
  `tb_usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_tb_pedido_tb_modelo_recurso1_idx` (`tb_modelo_recurso_idModelo` ASC),
  INDEX `fk_tb_pedido_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC),
  CONSTRAINT `fk_tb_pedido_tb_modelo_recurso1`
    FOREIGN KEY (`tb_modelo_recurso_idModelo`)
    REFERENCES `mydb`.`tb_modelo_recurso` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_carrinho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_carrinho` (
  `idCarrinho` INT NOT NULL AUTO_INCREMENT,
  `tb_pedido_idPedido` INT NOT NULL,
  `tb_usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCarrinho`),
  INDEX `fk_tb_carrinho_tb_pedido1_idx` (`tb_pedido_idPedido` ASC),
  INDEX `fk_tb_carrinho_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC),
  CONSTRAINT `fk_tb_carrinho_tb_pedido1`
    FOREIGN KEY (`tb_pedido_idPedido`)
    REFERENCES `mydb`.`tb_pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carrinho_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_pagamentos` (
  `idPagamamentos` INT NOT NULL AUTO_INCREMENT,
  `total` FLOAT NOT NULL,
  `tb_pedido_idPedido` INT NOT NULL,
  `tb_modelo_recurso_idModelo` INT NOT NULL,
  PRIMARY KEY (`idPagamamentos`),
  INDEX `fk_tb_pagamentos_tb_pedido1_idx` (`tb_pedido_idPedido` ASC),
  INDEX `fk_tb_pagamentos_tb_modelo_recurso1_idx` (`tb_modelo_recurso_idModelo` ASC),
  CONSTRAINT `fk_tb_pagamentos_tb_pedido1`
    FOREIGN KEY (`tb_pedido_idPedido`)
    REFERENCES `mydb`.`tb_pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pagamentos_tb_modelo_recurso1`
    FOREIGN KEY (`tb_modelo_recurso_idModelo`)
    REFERENCES `mydb`.`tb_modelo_recurso` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario_multa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_usuario_multa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario_multa` (
  `idUsuarioMulta` INT NOT NULL,
  `tb_multas_idMultas` INT NOT NULL,
  `tb_usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarioMulta`),
  INDEX `fk_tb_usuario_multa_tb_multas1_idx` (`tb_multas_idMultas` ASC),
  INDEX `fk_tb_usuario_multa_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC),
  CONSTRAINT `fk_tb_usuario_multa_tb_multas1`
    FOREIGN KEY (`tb_multas_idMultas`)
    REFERENCES `mydb`.`tb_multas` (`idMultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_multa_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_estadoCivil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_estadoCivil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_estadoCivil` (
  `idEstadoCivil` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstadoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuarioComplementar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_usuarioComplementar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuarioComplementar` (
  `idUsuarioComplementar` INT NOT NULL AUTO_INCREMENT,
  `tb_estadoCivil_idEstadoCivil` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NULL,
  `tb_usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarioComplementar`),
  INDEX `fk_tb_usuarioComplementar_tb_estadoCivil1_idx` (`tb_estadoCivil_idEstadoCivil` ASC),
  INDEX `fk_tb_usuarioComplementar_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC),
  CONSTRAINT `fk_tb_usuarioComplementar_tb_estadoCivil1`
    FOREIGN KEY (`tb_estadoCivil_idEstadoCivil`)
    REFERENCES `mydb`.`tb_estadoCivil` (`idEstadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuarioComplementar_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
